name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Java17のセットアップ
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Gradle wrapperの検証
        uses: gradle/wrapper-validation-action@v1

      - name: Wrapperの権限を設定
        run: chmod +x ./gradlew

      - name: Gradleでビルド
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: build/libs/*.jar
